title: Welcome to CodifyMe 🌟
description: Automate Your Infrastructure with Ease
logo: "/assets/images/codifyme_logo.png"
author: Ravi Joshi
email: ravijoshi1810@github.io
baseurl: "" # Leave empty for root hosting
#baseurl: "/fix-drift-terraform-import" # Uncomment if hosted under a subfolder
url: "https://ravijoshi1810.github.io/"
theme: just-the-docs
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
permalink: pretty
paginate: 5
nav_enabled: true
heading_anchors: true
just_the_docs:
  navigation:
    - title: "Home"
      url: "/"
    - title: "Blog Series"
      url: "/docs/blog-series/"