title: Welcome to CodifyMe 🌟 
description: Automate Your Infrastructure with Ease
author: Ravi Joshi
email: ravijoshi1810@github.io
baseurl: ""
#baseurl: "/fix-drift-terraform-import" # The repository name if hosted on GitHub Pages
url: "https://ravijoshi1810.github.io/" # Your GitHub Pages URL
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
permalink: pretty
paginate: 5
